spring:
    application:
        name: user-service
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # This will be overwritten by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: #spring.profiles.active#
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

    datasource:
            url: jdbc:mysql://${UWHIZ_DB_HOST}:3306/users?characterEncoding=UTF-8&useUnicode=true
            name: users
            username: ${UWHIZ_DB_USER}
            password: ${UWHIZ_DB_PASS}
            driverClassName: com.mysql.jdbc.Driver

liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
    contexts: default


security:
  oauth2:
    client:
      client-id: user-service
      client-secret: user-secret
      access-token-uri: http://localhost:8182/oauth/token
      user-authorization-uri: http://localhost:8182/oauth/authorize
    resource:
      user-info-uri: http://localhost:8182/me

logging:
  level:
    org.springframework.security: DEBUG


---
#spring:
#  application:
#    name: bankscraper-service
#  jpa:
#    show-sql: false
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: jdbc:hsqldb:mem:monitor;sql.syntax_mys=true
#---